name: Future proof tests
on:
  schedule:
    - cron: '35 23 * * 0' # Sun *-*-* 23:35:00 UTC
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_BACKTRACE: full

jobs:
  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-outdated
        uses: dtolnay/install@cargo-outdated

      - name: cargo-outdated
        run: rm -f Cargo.lock && cargo outdated --workspace --exit-code 1 --root-deps-only --exclude=clap,anstyle,clap_lex,regex,lsp-types
